// Constantes globales : alphabet, mots, couleurs
const String APP_TITLE = 'LetterQuest Kids';
const List<String> ALPHABET = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z'
];
const int STARS_PER_LETTER = 3;
const int TOTAL_LETTERS = 26;

// Mots clés par lettre (5 mots minimum par lettre)
const Map<String, List<String>> WORDS_BY_LETTER = {
  'A': ['Apple', 'Ant', 'Arrow', 'Anchor', 'Album'],
  'B': ['Book', 'Ball', 'Bear', 'Bicycle', 'Butterfly'],
  'C': ['Cat', 'Car', 'Cloud', 'Cake', 'Candle'],
  'D': ['Dog', 'Duck', 'Door', 'Drum', 'Diamond'],
  'E': ['Elephant', 'Egg', 'Eye', 'Eagle', 'Envelope'],
  'F': ['Fish', 'Fire', 'Flower', 'Flag', 'Frog'],
  'G': ['Grape', 'Guitar', 'Gate', 'Giraffe', 'Glove'],
  'H': ['House', 'Hat', 'Heart', 'Horse', 'Hammer'],
  'I': ['Ice', 'Igloo', 'Island', 'Iron', 'Ink'],
  'J': ['Jump', 'Jacket', 'Jar', 'Jellyfish', 'Jelly'],
  'K': ['Kite', 'King', 'Kitchen', 'Key', 'Kangaroo'],
  'L': ['Lion', 'Light', 'Leaf', 'Lemon', 'Ladder'],
  'M': ['Moon', 'Mouse', 'Mountain', 'Milk', 'Monkey'],
  'N': ['Nose', 'Nest', 'Nail', 'Neck', 'Net'],
  'O': ['Orange', 'Owl', 'Octopus', 'Oven', 'Oil'],
  'P': ['Penguin', 'Pig', 'Panda', 'Pizza', 'Pencil'],
  'Q': ['Queen', 'Quest', 'Quilt', 'Quiet', 'Quick'],
  'R': ['Rose', 'Rainbow', 'Robot', 'Ring', 'Rocket'],
  'S': ['Sun', 'Star', 'Snake', 'Ship', 'Smile'],
  'T': ['Tiger', 'Tree', 'Trumpet', 'Tent', 'Turtle'],
  'U': ['Umbrella', 'Unicorn', 'Universe', 'Unicycle', 'Underground'],
  'V': ['Violin', 'Van', 'Valley', 'Vase', 'Volcano'],
  'W': ['Whale', 'Wheel', 'Window', 'Watermelon', 'Wolf'],
  'X': ['Xylophone', 'X-ray', 'Xmas', 'Xerox', 'X-mark'],
  'Y': ['Yellow', 'Yoyo', 'Yacht', 'Yarn', 'Yawn'],
  'Z': ['Zebra', 'Zigzag', 'Zoo', 'Zero', 'Zip'],
};
// Objets simples à chercher avec la caméra par lettre
const Map<String, List<String>> OBJECTS_BY_LETTER = {
  'A': ['apple', 'animal', 'airplane'],
  'B': ['book', 'ball', 'banana', 'bottle', 'bag'],
  'C': ['cup', 'chair', 'cat', 'car', 'candle'],
  'D': ['dog', 'door', 'desk'],
  'E': ['egg', 'envelope'],
  'F': ['flower', 'food', 'fork'],
  'G': ['glass', 'glove'],
  'H': ['hat', 'house'],
  'I': ['ice'],
  'J': ['jacket'],
  'K': ['keyboard', 'key'],
  'L': ['laptop', 'lamp', 'leaf'],
  'M': ['mouse', 'mug', 'milk'],
  'N': ['notebook'],
  'O': ['orange'],
  'P': ['pencil', 'pen', 'phone', 'plant', 'paper'],
  'Q': ['quilt'],
  'R': ['ring', 'remote'],
  'S': ['shoe', 'spoon', 'star'],
  'T': ['table', 'toy', 'towel'],
  'U': ['umbrella'],
  'V': ['vase'],
  'W': ['watch', 'window'],
  'X': ['xylophone'],
  'Y': ['yoyo'],
  'Z': ['zip'],
};

const Map<String, List<String>> OBJECT_LABELS_BY_LETTER = {
  'A': ['airplane', 'aircraft', 'apple', 'ambulance', 'alarm clock', 'ant', 'anchor', 'armchair', 'apricot', 'asparagus', 'athlete', 'avenue', 'apartment', 'aquarium', 'arch'],
  'B': ['ball', 'book', 'bag', 'bicycle', 'butterfly', 'bottle', 'banana', 'bread', 'bench', 'backpack', 'bus', 'boat', 'bird', 'bear', 'bed', 'brush', 'bridge', 'building', 'bowl', 'burger', 'beverage', 'beer', 'biscuit', 'broom'],
  'C': ['cat', 'car', 'chair', 'cup', 'cake', 'camera', 'candle', 'clock', 'computer', 'couch', 'cupcake', 'coffee', 'cloud', 'clothing', 'coat', 'coin', 'cookie', 'corn', 'cow', 'crab', 'crayon', 'curtain', 'cycle', 'city', 'cafe', 'canal', 'castle', 'church', 'clinic'],
  'D': ['dog', 'duck', 'desk', 'door', 'doll', 'dish', 'dairy', 'desert', 'diamond', 'dinosaur', 'direction', 'disc', 'doctor', 'dolphin', 'doughnut', 'dress', 'drum', 'dustbin', 'dentist'],
  'E': ['egg', 'elephant', 'earphone', 'eraser', 'eagle', 'ear', 'earth', 'eel', 'eggplant', 'elbow', 'electric', 'elevator', 'engine', 'envelope', 'eye', 'exit'],
  'F': ['flower', 'food', 'flag', 'fork', 'fruit', 'fan', 'fish', 'face', 'factory', 'family', 'farm', 'feather', 'feet', 'field', 'finger', 'fire', 'firework', 'forest', 'fountain', 'fridge', 'frog', 'fry', 'furniture'],
  'G': ['glasses', 'garden', 'guitar', 'glove', 'glass', 'game', 'garlic', 'gate', 'gem', 'ghost', 'giraffe', 'girl', 'goat', 'gold', 'goldfish', 'goose', 'grape', 'grass', 'greenhouse', 'gym'],
  'H': ['hat', 'horse', 'house', 'hammer', 'handbag', 'hair', 'hand', 'harbor', 'heart', 'helicopter', 'helmet', 'highway', 'hill', 'honey', 'hospital', 'hotel', 'hot dog'],
  'I': ['ice', 'iron', 'island', 'ice cream', 'igloo', 'image', 'infant', 'insect', 'instrument', 'intercom'],
  'J': ['jacket', 'jar', 'juice', 'jaguar', 'jeans', 'jelly', 'jellyfish', 'jewelry', 'joint', 'journal', 'judge', 'jug', 'jungle'],
  'K': ['keyboard', 'kitchen', 'key', 'knife', 'kite', 'kangaroo', 'kettle', 'ketchup', 'keyboard', 'king', 'kitchenware', 'kitten', 'kiwi', 'knee', 'knight', 'knot'],
  'L': ['laptop', 'lamp', 'leaf', 'lemon', 'light', 'ladder', 'lake', 'lamb', 'landscape', 'lantern', 'law', 'layer', 'leaf', 'leather', 'leg', 'lemonade', 'lens', 'letter', 'library', 'life', 'lily', 'line', 'lion', 'lips', 'litter', 'lizard', 'lock', 'log', 'lorry', 'loudspeaker', 'lunch'],
  'M': ['mouse', 'mobile phone', 'mug', 'milk', 'mountain', 'mirror', 'microphone', 'machine', 'magazine', 'magnet', 'mail', 'map', 'marble', 'market', 'mask', 'match', 'meal', 'meat', 'medal', 'medicine', 'melon', 'menu', 'message', 'metal', 'meter', 'mill', 'mistletoe', 'money', 'monitor', 'monkey', 'moon', 'motorcycle', 'mouth', 'mud', 'muffin', 'mushroom', 'music'],
  'N': ['notebook', 'net', 'necktie', 'nail', 'napkin', 'necklace', 'needle', 'nest', 'newspaper', 'night', 'nose', 'note', 'nozzle', 'nut'],
  'O': ['orange', 'oven', 'owl', 'oak', 'oar', 'ocean', 'office', 'oil', 'onion', 'opera', 'optical', 'orchestra', 'organ', 'ostrich', 'otter', 'outlet', 'ox'],
  'P': ['pencil', 'phone', 'plant', 'paper', 'pizza', 'pen', 'plate', 'pillow', 'piano', 'packet', 'pad', 'page', 'pail', 'paint', 'palace', 'palm', 'pan', 'pancake', 'panda', 'paper', 'parachute', 'parade', 'park', 'parrot', 'part', 'passenger', 'pastry', 'path', 'pattern', 'pavement', 'pea', 'peach', 'peacock', 'pear', 'pebble', 'pedal', 'pelican', 'pen', 'pencil', 'penguin', 'people', 'pepper', 'perfume', 'person', 'pet', 'petal', 'phone', 'photo', 'piano', 'picnic', 'picture', 'pie', 'pig', 'pigeon', 'pill', 'pillow', 'pilot', 'pin', 'pine', 'pipe', 'pirate', 'pizza', 'plane', 'planet', 'plant', 'plate', 'platform', 'play', 'player', 'playground', 'plot', 'plough', 'pocket', 'poem', 'point', 'poison', 'pole', 'police', 'policeman', 'pond', 'pony', 'pool', 'popcorn', 'port', 'post', 'pot', 'potato', 'pottery', 'pouch', 'poultry', 'powder', 'prawn', 'present', 'press', 'price', 'priest', 'printer', 'prison', 'prize', 'produce', 'product', 'professor', 'profile', 'programme', 'project', 'property', 'protest', 'pudding', 'puddle', 'pump', 'pumpkin', 'puppet', 'puppy', 'purse', 'puzzle', 'pyramid'],
  'Q': ['quilt', 'quarter', 'queen', 'question', 'quill', 'quiver'],
  'R': ['ring', 'rocket', 'rainbow', 'remote', 'refrigerator', 'radio', 'rabbit', 'race', 'rack', 'radar', 'radiator', 'rail', 'railway', 'rain', 'rake', 'rat', 'razor', 'receipt', 'record', 'red', 'reed', 'reef', 'referee', 'register', 'reindeer', 'restaurant', 'ribbon', 'rice', 'rifle', 'ring', 'river', 'road', 'robot', 'rock', 'rocket', 'rod', 'roll', 'roof', 'room', 'root', 'rope', 'rose', 'round', 'route', 'row', 'rubber', 'ruby', 'rug', 'rule', 'ruler', 'run', 'runner'],
  'S': ['shoe', 'star', 'spoon', 'socks', 'shirt', 'sandwich', 'scissors', 'soap', 'sunglasses', 'sack', 'saddle', 'sail', 'salad', 'salt', 'sand', 'sauce', 'saucer', 'sausage', 'scale', 'scarf', 'scene', 'school', 'science', 'screen', 'screw', 'sculpture', 'sea', 'seal', 'seat', 'seed', 'sentence', 'servant', 'shade', 'shadow', 'shampoo', 'shape', 'shark', 'sheep', 'sheet', 'shelf', 'shell', 'shield', 'ship', 'shirt', 'shoe', 'shop', 'shoulder', 'shovel', 'shrimp', 'shrine', 'shutter', 'sidewalk', 'sign', 'silk', 'silver', 'sink', 'sister', 'skate', 'skeleton', 'ski', 'skin', 'skirt', 'sky', 'skyscraper', 'sledge', 'sleep', 'sleeve', 'slide', 'slipper', 'slope', 'smile', 'smoke', 'snail', 'snake', 'snow', 'soap', 'sock', 'sofa', 'soft', 'soil', 'soldier', 'son', 'song', 'soup', 'space', 'spade', 'spaghetti', 'spark', 'sparrow', 'speaker', 'spear', 'spectacles', 'speed', 'spider', 'spike', 'spinach', 'sponge', 'spoon', 'sport', 'spot', 'spray', 'spring', 'spur', 'square', 'squid', 'squirrel', 'stable', 'stack', 'stadium', 'staff', 'stage', 'stair', 'stamp', 'star', 'station', 'statue', 'steak', 'steam', 'steel', 'stem', 'step', 'stick', 'stitch', 'stocking', 'stomach', 'stone', 'stool', 'stop', 'store', 'storm', 'story', 'stove', 'strap', 'straw', 'strawberry', 'stream', 'street', 'string', 'stripe', 'structure', 'student', 'studio', 'study', 'subway', 'sugar', 'suit', 'suitcase', 'sun', 'sunflower', 'sunlight', 'supermarket', 'surf', 'surface', 'surgeon', 'swan', 'sweater', 'sweets', 'swim', 'swing', 'switch', 'sword', 'syrup', 'system'],
  'T': ['table', 'toy', 'turtle', 'towel', 'toothbrush', 'television', 'telephone', 'train', 'truck', 'tablet', 'tail', 'tank', 'tap', 'tape', 'target', 'tea', 'teapot', 'tear', 'technique', 'teeth', 'telescope', 'temple', 'tennis', 'tent', 'terminal', 'terrace', 'text', 'theatre', 'thermometer', 'thigh', 'thimble', 'thread', 'throat', 'throne', 'thumb', 'ticket', 'tie', 'tiger', 'tile', 'time', 'tin', 'toast', 'toe', 'toilet', 'tomato', 'tongue', 'tool', 'tooth', 'top', 'torch', 'tortoise', 'tower', 'town', 'toy', 'track', 'tractor', 'traffic', 'trail', 'train', 'tram', 'tray', 'tree', 'triangle', 'trick', 'trolley', 'trumpet', 'trunk', 'tube', 'tulip', 'tuna', 'tunnel', 'turkey', 'turnip', 'turtle', 'twig', 'type', 'tyre'],
  'U': ['umbrella', 'unicycle', 'uncle', 'underground', 'underwear', 'unit', 'universe', 'university', 'urn', 'utensil'],
  'V': ['van', 'vase', 'violin', 'vegetable', 'valley', 'valve', 'vampire', 'vane', 'vault', 'vehicle', 'veil', 'vein', 'velvet', 'vessel', 'vest', 'vial', 'victim', 'video', 'view', 'village', 'vine', 'vinegar', 'violin', 'visa', 'visage', 'visitor', 'voice', 'volcano', 'vulture'],
  'W': ['watch', 'window', 'wallet', 'wheel', 'wagon', 'waist', 'waiter', 'wall', 'walnut', 'warehouse', 'warrior', 'wash', 'wasp', 'waste', 'water', 'waterfall', 'watermelon', 'wave', 'wax', 'way', 'weapon', 'weather', 'web', 'wedding', 'wedge', 'weed', 'week', 'weight', 'whale', 'wheat', 'wheel', 'whip', 'whistle', 'white', 'wig', 'wild', 'willow', 'wind', 'window', 'wine', 'wing', 'winter', 'wire', 'wish', 'witch', 'witness', 'wolf', 'woman', 'wood', 'wool', 'word', 'work', 'worker', 'world', 'worm', 'wrist', 'writing'],
  'X': ['xylophone', 'x-ray', 'xmas', 'x-mark'],
  'Y': ['yoyo', 'yacht', 'yak', 'yam', 'yard', 'yarn', 'year', 'yellow', 'yew', 'yoke', 'yolk', 'young'],
  'Z': ['zebra', 'zip', 'zero', 'zigzag', 'zinc', 'zone', 'zoo'],
};

const Map<String, String> OBJECT_LABELS_FR = {
  'airplane': 'avion',
  'aircraft': 'avion',
  'ambulance': 'ambulance',
  'alarm clock': 'réveil',
  'ant': 'fourmi',
  'anchor': 'ancre',
  'armchair': 'fauteuil',
  'apricot': 'abricot',
  'asparagus': 'asperge',
  'athlete': 'athlète',
  'avenue': 'avenue',
  'apartment': 'appartement',
  'aquarium': 'aquarium',
  'arch': 'arche',
  'apple': 'pomme',
  'ball': 'balle',
  'book': 'livre',
  'bag': 'sac',
  'bicycle': 'vélo',
  'butterfly': 'papillon',
  'bottle': 'bouteille',
  'banana': 'banane',
  'bread': 'pain',
  'bench': 'banc',
  'backpack': 'sac à dos',
  'bus': 'bus',
  'boat': 'bateau',
  'bird': 'oiseau',
  'bear': 'ours',
  'bed': 'lit',
  'brush': 'pinceau',
  'bridge': 'pont',
  'building': 'immeuble',
  'bowl': 'bol',
  'burger': 'hamburger',
  'beverage': 'boisson',
  'beer': 'bière',
  'biscuit': 'biscuit',
  'broom': 'balai',
  'cat': 'chat',
  'car': 'voiture',
  'chair': 'chaise',
  'cup': 'tasse',
  'cake': 'gâteau',
  'camera': 'appareil photo',
  'candle': 'bougie',
  'clock': 'horloge',
  'computer': 'ordinateur',
  'couch': 'canapé',
  'cupcake': 'cupcake',
  'coffee': 'café',
  'cloud': 'nuage',
  'clothing': 'vêtements',
  'coat': 'manteau',
  'coin': 'pièce',
  'cookie': 'biscuit',
  'corn': 'maïs',
  'cow': 'vache',
  'crab': 'crabe',
  'crayon': 'crayon',
  'curtain': 'rideau',
  'cycle': 'cycle',
  'city': 'ville',
  'cafe': 'café',
  'canal': 'canal',
  'castle': 'château',
  'church': 'église',
  'clinic': 'clinique',
  'dog': 'chien',
  'duck': 'canard',
  'desk': 'bureau',
  'door': 'porte',
  'doll': 'poupée',
  'dish': 'plat',
  'dairy': 'produit laitier',
  'desert': 'désert',
  'diamond': 'diamant',
  'dinosaur': 'dinosaure',
  'direction': 'direction',
  'disc': 'disque',
  'doctor': 'docteur',
  'dolphin': 'dauphin',
  'doughnut': 'beignet',
  'dress': 'robe',
  'drum': 'tambour',
  'dustbin': 'poubelle',
  'dentist': 'dentiste',
  'egg': 'œuf',
  'elephant': 'éléphant',
  'earphone': 'écouteurs',
  'eraser': 'gomme',
  'eagle': 'aigle',
  'ear': 'oreille',
  'earth': 'terre',
  'eel': 'anguille',
  'eggplant': 'aubergine',
  'elbow': 'coude',
  'electric': 'électrique',
  'elevator': 'ascenseur',
  'engine': 'moteur',
  'envelope': 'enveloppe',
  'eye': 'œil',
  'exit': 'sortie',
  'flower': 'fleur',
  'food': 'nourriture',
  'flag': 'drapeau',
  'fork': 'fourchette',
  'fruit': 'fruit',
  'fan': 'ventilateur',
  'fish': 'poisson',
  'face': 'visage',
  'factory': 'usine',
  'family': 'famille',
  'farm': 'ferme',
  'feather': 'plume',
  'feet': 'pieds',
  'field': 'champ',
  'finger': 'doigt',
  'fire': 'feu',
  'firework': 'feu d\'artifice',
  'forest': 'forêt',
  'fountain': 'fontaine',
  'fridge': 'frigo',
  'frog': 'grenouille',
  'fry': 'friture',
  'furniture': 'meuble',
  'glasses': 'lunettes',
  'garden': 'jardin',
  'guitar': 'guitare',
  'glove': 'gant',
  'glass': 'verre',
  'game': 'jeu',
  'garlic': 'ail',
  'gate': 'porte',
  'gem': 'gemme',
  'ghost': 'fantôme',
  'giraffe': 'girafe',
  'girl': 'fille',
  'goat': 'chèvre',
  'gold': 'or',
  'goldfish': 'poisson rouge',
  'goose': 'oie',
  'grape': 'raisin',
  'grass': 'herbe',
  'greenhouse': 'serre',
  'gym': 'gym',
  'hat': 'chapeau',
  'horse': 'cheval',
  'house': 'maison',
  'hammer': 'marteau',
  'handbag': 'sac à main',
  'hair': 'cheveux',
  'hand': 'main',
  'harbor': 'port',
  'heart': 'cœur',
  'helicopter': 'hélicoptère',
  'helmet': 'casque',
  'highway': 'autoroute',
  'hill': 'colline',
  'honey': 'miel',
  'hospital': 'hôpital',
  'hotel': 'hôtel',
  'hot dog': 'hot-dog',
  'ice': 'glace',
  'iron': 'fer à repasser',
  'island': 'île',
  'ice cream': 'glace',
  'igloo': 'igloo',
  'image': 'image',
  'infant': 'nourrisson',
  'insect': 'insecte',
  'instrument': 'instrument',
  'intercom': 'interphone',
  'jacket': 'veste',
  'jar': 'pot',
  'juice': 'jus',
  'jaguar': 'jaguar',
  'jeans': 'jean',
  'jelly': 'gelée',
  'jellyfish': 'méduse',
  'jewelry': 'bijoux',
  'joint': 'jointure',
  'journal': 'journal',
  'judge': 'juge',
  'jug': 'cruche',
  'jungle': 'jungle',
  'keyboard': 'clavier',
  'kitchen': 'cuisine',
  'key': 'clé',
  'knife': 'couteau',
  'kite': 'cerf-volant',
  'kangaroo': 'kangourou',
  'kettle': 'bouilloire',
  'ketchup': 'ketchup',
  'king': 'roi',
  'kitchenware': 'ustensiles de cuisine',
  'kitten': 'chaton',
  'kiwi': 'kiwi',
  'knee': 'genou',
  'knight': 'chevalier',
  'knot': 'nœud',
  'laptop': 'ordinateur portable',
  'lamp': 'lampe',
  'leaf': 'feuille',
  'lemon': 'citron',
  'light': 'lumière',
  'ladder': 'échelle',
  'lake': 'lac',
  'lamb': 'agneau',
  'landscape': 'paysage',
  'lantern': 'lanterne',
  'law': 'loi',
  'layer': 'couche',
  'leather': 'cuir',
  'leg': 'jambe',
  'lemonade': 'limonade',
  'lens': 'lentille',
  'letter': 'lettre',
  'library': 'bibliothèque',
  'life': 'vie',
  'lily': 'lis',
  'line': 'ligne',
  'lion': 'lion',
  'lips': 'lèvres',
  'litter': 'litière',
  'lizard': 'lézard',
  'lock': 'serrure',
  'log': 'bûche',
  'lorry': 'camion',
  'loudspeaker': 'haut-parleur',
  'lunch': 'déjeuner',
  'mouse': 'souris',
  'mobile phone': 'téléphone',
  'mug': 'tasse',
  'milk': 'lait',
  'mountain': 'montagne',
  'mirror': 'miroir',
  'microphone': 'microphone',
  'machine': 'machine',
  'magazine': 'magazine',
  'magnet': 'aimant',
  'mail': 'courrier',
  'map': 'carte',
  'marble': 'marbre',
  'market': 'marché',
  'mask': 'masque',
  'match': 'allumette',
  'meal': 'repas',
  'meat': 'viande',
  'medal': 'médaille',
  'medicine': 'médicament',
  'melon': 'melon',
  'menu': 'menu',
  'message': 'message',
  'metal': 'métal',
  'meter': 'mètre',
  'mill': 'moulin',
  'mistletoe': 'gui',
  'money': 'argent',
  'monitor': 'écran',
  'monkey': 'singe',
  'moon': 'lune',
  'motorcycle': 'moto',
  'mouth': 'bouche',
  'mud': 'boue',
  'muffin': 'muffin',
  'mushroom': 'champignon',
  'music': 'musique',
  'notebook': 'carnet',
  'net': 'filet',
  'necktie': 'cravate',
  'nail': 'clou',
  'napkin': 'serviette',
  'necklace': 'collier',
  'needle': 'aiguille',
  'nest': 'nid',
  'newspaper': 'journal',
  'night': 'nuit',
  'nose': 'nez',
  'note': 'note',
  'nozzle': 'buse',
  'nut': 'noix',
  'orange': 'orange',
  'oven': 'four',
  'owl': 'hibou',
  'oak': 'chêne',
  'oar': 'rame',
  'ocean': 'océan',
  'office': 'bureau',
  'oil': 'huile',
  'onion': 'oignon',
  'opera': 'opéra',
  'optical': 'optique',
  'orchestra': 'orchestre',
  'organ': 'orgue',
  'ostrich': 'autruche',
  'otter': 'loutre',
  'outlet': 'prise',
  'ox': 'bœuf',
  'pencil': 'crayon',
  'phone': 'téléphone',
  'plant': 'plante',
  'paper': 'papier',
  'pizza': 'pizza',
  'pen': 'stylo',
  'plate': 'assiette',
  'pillow': 'oreiller',
  'piano': 'piano',
  'packet': 'paquet',
  'pad': 'bloc-notes',
  'page': 'page',
  'pail': 'seau',
  'paint': 'peinture',
  'palace': 'palais',
  'palm': 'paume',
  'pan': 'poêle',
  'pancake': 'crêpe',
  'panda': 'panda',
  'parachute': 'parachute',
  'parade': 'parade',
  'park': 'parc',
  'parrot': 'perroquet',
  'part': 'partie',
  'passenger': 'passager',
  'pastry': 'pâtisserie',
  'path': 'chemin',
  'pattern': 'motif',
  'pavement': 'trottoir',
  'pea': 'pois',
  'peach': 'pêche',
  'peacock': 'paon',
  'pear': 'poire',
  'pebble': 'caillou',
  'pedal': 'pédale',
  'pelican': 'pélican',
  'penguin': 'pingouin',
  'people': 'gens',
  'pepper': 'poivre',
  'perfume': 'parfum',
  'person': 'personne',
  'pet': 'animal de compagnie',
  'petal': 'pétale',
  'photo': 'photo',
  'picnic': 'pique-nique',
  'picture': 'image',
  'pie': 'tarte',
  'pig': 'cochon',
  'pigeon': 'pigeon',
  'pill': 'pilule',
  'pilot': 'pilote',
  'pin': 'épingle',
  'pine': 'pin',
  'pipe': 'tuyau',
  'pirate': 'pirate',
  'plane': 'avion',
  'planet': 'planète',
  'platform': 'plate-forme',
  'play': 'jeu',
  'player': 'joueur',
  'playground': 'terrain de jeu',
  'plot': 'parcelle',
  'plough': 'charrue',
  'pocket': 'poche',
  'poem': 'poème',
  'point': 'point',
  'poison': 'poison',
  'pole': 'poteau',
  'police': 'police',
  'policeman': 'policier',
  'pond': 'étang',
  'pony': 'poney',
  'pool': 'piscine',
  'popcorn': 'popcorn',
  'port': 'port',
  'post': 'poste',
  'pot': 'pot',
  'potato': 'pomme de terre',
  'pottery': 'poterie',
  'pouch': 'pochette',
  'poultry': 'volaille',
  'powder': 'poudre',
  'prawn': 'crevette',
  'present': 'cadeau',
  'press': 'presse',
  'price': 'prix',
  'priest': 'prêtre',
  'printer': 'imprimante',
  'prison': 'prison',
  'prize': 'prix',
  'produce': 'produit',
  'product': 'produit',
  'professor': 'professeur',
  'profile': 'profil',
  'programme': 'programme',
  'project': 'projet',
  'property': 'propriété',
  'protest': 'protestation',
  'pudding': 'pudding',
  'puddle': 'flaque',
  'pump': 'pompe',
  'pumpkin': 'citrouille',
  'puppet': 'marionnette',
  'puppy': 'chiot',
  'purse': 'sac à main',
  'puzzle': 'puzzle',
  'pyramid': 'pyramide',
  'quilt': 'couverture',
  'quarter': 'quart',
  'queen': 'reine',
  'question': 'question',
  'quill': 'plume',
  'quiver': 'carquois',
  'ring': 'bague',
  'rocket': 'fusée',
  'rainbow': 'arc-en-ciel',
  'remote': 'télécommande',
  'refrigerator': 'réfrigérateur',
  'radio': 'radio',
  'rabbit': 'lapin',
  'race': 'course',
  'rack': 'étagère',
  'radar': 'radar',
  'radiator': 'radiateur',
  'rail': 'rail',
  'railway': 'chemin de fer',
  'rain': 'pluie',
  'rake': 'râteau',
  'rat': 'rat',
  'razor': 'rasoir',
  'receipt': 'reçu',
  'record': 'disque',
  'red': 'rouge',
  'reed': 'roseau',
  'reef': 'récif',
  'referee': 'arbitre',
  'register': 'registre',
  'reindeer': 'renne',
  'restaurant': 'restaurant',
  'ribbon': 'ruban',
  'rice': 'riz',
  'rifle': 'fusil',
  'river': 'rivière',
  'road': 'route',
  'robot': 'robot',
  'rock': 'rocher',
  'rod': 'tige',
  'roll': 'rouleau',
  'roof': 'toit',
  'room': 'chambre',
  'root': 'racine',
  'rope': 'corde',
  'rose': 'rose',
  'round': 'rond',
  'route': 'itinéraire',
  'row': 'rangée',
  'rubber': 'caoutchouc',
  'ruby': 'rubis',
  'rug': 'tapis',
  'rule': 'règle',
  'ruler': 'règle',
  'run': 'course',
  'runner': 'coureur',
  'shoe': 'chaussure',
  'star': 'étoile',
  'spoon': 'cuillère',
  'socks': 'chaussettes',
  'shirt': 'chemise',
  'sandwich': 'sandwich',
  'scissors': 'ciseaux',
  'soap': 'savon',
  'sunglasses': 'lunettes de soleil',
  'sack': 'sac',
  'saddle': 'selle',
  'sail': 'voile',
  'salad': 'salade',
  'salt': 'sel',
  'sand': 'sable',
  'sauce': 'sauce',
  'saucer': 'soucoupe',
  'sausage': 'saucisse',
  'scale': 'échelle',
  'scarf': 'écharpe',
  'scene': 'scène',
  'school': 'école',
  'science': 'science',
  'screen': 'écran',
  'screw': 'vis',
  'sculpture': 'sculpture',
  'sea': 'mer',
  'seal': 'phoque',
  'seat': 'siège',
  'seed': 'graine',
  'sentence': 'phrase',
  'servant': 'serviteur',
  'shade': 'ombre',
  'shadow': 'ombre',
  'shampoo': 'shampooing',
  'shape': 'forme',
  'shark': 'requin',
  'sheep': 'mouton',
  'sheet': 'drap',
  'shelf': 'étagère',
  'shell': 'coquille',
  'shield': 'bouclier',
  'ship': 'navire',
  'shop': 'magasin',
  'shoulder': 'épaule',
  'shovel': 'pelle',
  'shrimp': 'crevette',
  'shrine': 'sanctuaire',
  'shutter': 'volet',
  'sidewalk': 'trottoir',
  'sign': 'panneau',
  'silk': 'soie',
  'silver': 'argent',
  'sink': 'évier',
  'sister': 'sœur',
  'skate': 'patin',
  'skeleton': 'squelette',
  'ski': 'ski',
  'skin': 'peau',
  'skirt': 'jupe',
  'sky': 'ciel',
  'skyscraper': 'gratte-ciel',
  'sledge': 'traîneau',
  'sleep': 'sommeil',
  'sleeve': 'manche',
  'slide': 'toboggan',
  'slipper': 'pantoufle',
  'slope': 'pente',
  'smile': 'sourire',
  'smoke': 'fumée',
  'snail': 'escargot',
  'snake': 'serpent',
  'snow': 'neige',
  'sock': 'chaussette',
  'sofa': 'canapé',
  'soft': 'doux',
  'soil': 'sol',
  'soldier': 'soldat',
  'son': 'fils',
  'song': 'chanson',
  'soup': 'soupe',
  'space': 'espace',
  'spade': 'bêche',
  'spaghetti': 'spaghetti',
  'spark': 'étincelle',
  'sparrow': 'moineau',
  'speaker': 'haut-parleur',
  'spear': 'lance',
  'spectacles': 'lunettes',
  'speed': 'vitesse',
  'spider': 'araignée',
  'spike': 'pointe',
  'spinach': 'épinards',
  'sponge': 'éponge',
  'sport': 'sport',
  'spot': 'tache',
  'spray': 'spray',
  'spring': 'printemps',
  'spur': 'éperon',
  'square': 'carré',
  'squid': 'calmar',
  'squirrel': 'écureuil',
  'stable': 'écurie',
  'stack': 'pile',
  'stadium': 'stade',
  'staff': 'personnel',
  'stage': 'scène',
  'stair': 'escalier',
  'stamp': 'timbre',
  'station': 'station',
  'statue': 'statue',
  'steak': 'steak',
  'steam': 'vapeur',
  'steel': 'acier',
  'stem': 'tige',
  'step': 'étape',
  'stick': 'bâton',
  'stitch': 'point',
  'stocking': 'bas',
  'stomach': 'estomac',
  'stone': 'pierre',
  'stool': 'tabouret',
  'stop': 'arrêt',
  'store': 'magasin',
  'storm': 'tempête',
  'story': 'histoire',
  'stove': 'cuisinière',
  'strap': 'sangle',
  'straw': 'paille',
  'strawberry': 'fraise',
  'stream': 'ruisseau',
  'street': 'rue',
  'string': 'ficelle',
  'stripe': 'rayure',
  'structure': 'structure',
  'student': 'étudiant',
  'studio': 'studio',
  'study': 'étude',
  'subway': 'métro',
  'sugar': 'sucre',
  'suit': 'costume',
  'suitcase': 'valise',
  'sun': 'soleil',
  'sunflower': 'tournesol',
  'sunlight': 'lumière du soleil',
  'supermarket': 'supermarché',
  'surf': 'surf',
  'surface': 'surface',
  'surgeon': 'chirurgien',
  'swan': 'cygne',
  'sweater': 'pull',
  'sweets': 'bonbons',
  'swim': 'natation',
  'swing': 'balançoire',
  'switch': 'interrupteur',
  'sword': 'épée',
  'syrup': 'sirop',
  'system': 'système',
  'table': 'table',
  'toy': 'jouet',
  'turtle': 'tortue',
  'towel': 'serviette',
  'toothbrush': 'brosse à dents',
  'television': 'télévision',
  'telephone': 'téléphone',
  'train': 'train',
  'truck': 'camion',
  'tablet': 'tablette',
  'tail': 'queue',
  'tank': 'réservoir',
  'tap': 'robinet',
  'tape': 'ruban adhésif',
  'target': 'cible',
  'tea': 'thé',
  'teapot': 'théière',
  'tear': 'larme',
  'technique': 'technique',
  'teeth': 'dents',
  'telescope': 'télescope',
  'temple': 'temple',
  'tennis': 'tennis',
  'tent': 'tente',
  'terminal': 'terminal',
  'terrace': 'terrasse',
  'text': 'texte',
  'theatre': 'théâtre',
  'thermometer': 'thermomètre',
  'thigh': 'cuisse',
  'thimble': 'dé à coudre',
  'thread': 'fil',
  'throat': 'gorge',
  'throne': 'trône',
  'thumb': 'pouce',
  'ticket': 'billet',
  'tie': 'cravate',
  'tiger': 'tigre',
  'tile': 'tuile',
  'time': 'temps',
  'tin': 'boîte',
  'toast': 'toast',
  'toe': 'orteil',
  'toilet': 'toilettes',
  'tomato': 'tomate',
  'tongue': 'langue',
  'tool': 'outil',
  'tooth': 'dent',
  'top': 'sommet',
  'torch': 'lampe torche',
  'tortoise': 'tortue',
  'tower': 'tour',
  'town': 'ville',
  'track': 'piste',
  'tractor': 'tracteur',
  'traffic': 'trafic',
  'trail': 'sentier',
  'tram': 'tramway',
  'tray': 'plateau',
  'tree': 'arbre',
  'triangle': 'triangle',
  'trick': 'tour',
  'trolley': 'chariot',
  'trumpet': 'trompette',
  'trunk': 'tronc',
  'tube': 'tube',
  'tulip': 'tulipe',
  'tuna': 'thon',
  'tunnel': 'tunnel',
  'turkey': 'dinde',
  'turnip': 'navet',
  'twig': 'brindille',
  'type': 'type',
  'tyre': 'pneu',
  'umbrella': 'parapluie',
  'unicycle': 'monocycle',
  'uncle': 'oncle',
  'underground': 'souterrain',
  'underwear': 'sous-vêtements',
  'unit': 'unité',
  'universe': 'univers',
  'university': 'université',
  'urn': 'urne',
  'utensil': 'ustensile',
  'van': 'camionnette',
  'vase': 'vase',
  'violin': 'violon',
  'vegetable': 'légume',
  'valley': 'vallée',
  'valve': 'valve',
  'vampire': 'vampire',
  'vane': 'girouette',
  'vault': 'voûte',
  'vehicle': 'véhicule',
  'veil': 'voile',
  'vein': 'veine',
  'velvet': 'velours',
  'vessel': 'vaisseau',
  'vest': 'gilet',
  'vial': 'fiole',
  'victim': 'victime',
  'video': 'vidéo',
  'view': 'vue',
  'village': 'village',
  'vine': 'vigne',
  'vinegar': 'vinaigre',
  'visa': 'visa',
  'visage': 'visage',
  'visitor': 'visiteur',
  'voice': 'voix',
  'volcano': 'volcan',
  'vulture': 'vautour',
  'watch': 'montre',
  'window': 'fenêtre',
  'wallet': 'portefeuille',
  'wheel': 'roue',
  'wagon': 'wagon',
  'waist': 'taille',
  'waiter': 'serveur',
  'wall': 'mur',
  'walnut': 'noix',
  'warehouse': 'entrepôt',
  'warrior': 'guerrier',
  'wash': 'lavage',
  'wasp': 'guêpe',
  'waste': 'déchet',
  'water': 'eau',
  'waterfall': 'cascade',
  'watermelon': 'pastèque',
  'wave': 'vague',
  'wax': 'cire',
  'way': 'chemin',
  'weapon': 'arme',
  'weather': 'météo',
  'web': 'toile',
  'wedding': 'mariage',
  'wedge': 'coin',
  'weed': 'mauvaise herbe',
  'week': 'semaine',
  'weight': 'poids',
  'whale': 'baleine',
  'wheat': 'blé',
  'whip': 'fouet',
  'whistle': 'sifflet',
  'white': 'blanc',
  'wig': 'perruque',
  'wild': 'sauvage',
  'willow': 'saule',
  'wind': 'vent',
  'wine': 'vin',
  'wing': 'aile',
  'winter': 'hiver',
  'wire': 'fil de fer',
  'wish': 'vœu',
  'witch': 'sorcière',
  'witness': 'témoin',
  'wolf': 'loup',
  'woman': 'femme',
  'wood': 'bois',
  'wool': 'laine',
  'word': 'mot',
  'work': 'travail',
  'worker': 'ouvrier',
  'world': 'monde',
  'worm': 'ver',
  'wrist': 'poignet',
  'writing': 'écriture',
  'xylophone': 'xylophone',
  'x-ray': 'radiographie',
  'xmas': 'noël',
  'x-mark': 'croix',
  'yoyo': 'yoyo',
  'yacht': 'yacht',
  'yak': 'yak',
  'yam': 'igname',
  'yard': 'cour',
  'yarn': 'fil',
  'year': 'année',
  'yellow': 'jaune',
  'yew': 'if',
  'yoke': 'joug',
  'yolk': 'jaune d\'œuf',
  'young': 'jeune',
  'zebra': 'zèbre',
  'zip': 'fermeture éclair',
  'zero': 'zéro',
  'zigzag': 'zigzag',
  'zinc': 'zinc',
  'zone': 'zone',
  'zoo': 'zoo',
};
